site_name: Swinburne Rover Team Wiki
theme:
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  language: en
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

plugins:
  - tags
